spring:
  application:
    name: coupons-api
  session:
    store-type: none
  profiles:
    active: local
  datasource:
    url: jdbc:postgresql://localhost:5432/test?user=root&password=secret
    hikari:
      schema: test
  jpa:
    database: postgresql
    open-in-view: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        default_schema: test

  flyway:
    enabled: true
    baseline-on-migrate: true
    baseline-version: 0
    schemas: test

  security:
    user:
      name: "user"
      password: "password"

springdoc:
  swagger-ui:
    tagsSorter: alpha
  api-docs:
    groups:
      enabled: true

server:
  port: 8091
  servlet:
    context-path: /
  compression:
    enabled: true

management:
  endpoints:
    enabled-by-default: false
    web:
      exposure:
        include: health,info
      base-path: /.well-known
      path-mapping:
        info: ready
        health: live
  endpoint:
    info:
      enabled: true
    health:
      enabled: true

logging:
  level:
    org.hibernate:
      SQL: DEBUG

---
spring:
  config:
    activate:
      on-profile: local

  datasource:
    url: jdbc:postgresql://localhost:5432/test?user=root&password=secret
  jpa:
    properties:
      hibernate:
        ddl-auto: validate
        format_sql: true
