openapi: 3.0.1
info:
  title: Coupon API
  description: This API provides list of valid coupons of a member. List is sorted by valid until date. If Latitude and longitude provided as a parameters then API returns coupon list sorted by distance.
  contact:
    name: Coupons Management
    url: https://coupon-xxx.de
    email: coupons@xxx.de
  version: 1.0.0
  x-business-objects:
    - Coupons
  x-business-domain: Coupon
  x-product: Coupons
servers:
  - url: http://localhost:8091/
    description: Coupons API local Environment
security:
  - Basic-Authentication: []
paths:
  /member-coupons/{memberId}:
    get:
      tags:
        - member-coupons-controller
      operationId: getAllValidMemberCoupons
      parameters:
        - name: memberId
          in: path
          description: Id of `Member`
          required: true
          schema:
            type: string
          example: 12345
        - name: latitude
          in: query
          required: false
          schema:
            type: string
        - name: longitude
          in: query
          required: false
          schema:
            type: string
      responses:
        '200':
          description: Returns a list of valid coupons
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Coupons'
components:
  schemas:
    Coupon:
      type: object
      properties:
        couponId:
          type: string
        validFrom:
          type: string
          format: date
        validUntil:
          type: string
          format: date
        distance:
          type: number
          format: double
        city:
          type: string
    Coupons:
      type: object
      properties:
        couponList:
          type: array
          items:
            $ref: '#/components/schemas/Coupon'
  securitySchemes:
    Basic-Authentication:
      type: http
      scheme: basic
